# -*- coding: utf-8 -*-
"""LinearRegression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fRdB64ca_j2qP4A7nPelb42zKlrE1TZ6
"""

import pandas as pd
import numpy as np
from google.colab import drive

from pandas import read_csv

# Load the dataset
drive.mount('/content/drive')

df = pd.read_csv('/content/drive/My Drive/HeatingCost.csv')

df.head()

import seaborn as sns
import matplotlib.pyplot as plt
#pairplot of Heatin cost against Age
sns.pairplot(df, x_vars=['Age'], y_vars=['Heating Cost'])
plt.show()

# Save resulting DataFrame in a separate variable to prepare for regression
#data1 = df[["Age", "Heating Cost"]]
#data1.head()

X=df[["Age"]]
Y = df[["Heating Cost"]]

from sklearn.linear_model import LinearRegression

model= LinearRegression()
model.fit(Age,Heating)
# Get results
slope = model.coef_[0]
intercept = model.intercept_
r_squared = model.score(X, Y)

print(f"Slope: {slope}")
print(f"Intercept: {intercept}")
print(f"R²: {r_squared}")

import seaborn as sns
import matplotlib.pyplot as plt

# Create scatterplot with regression line
sns.regplot(x=df["Age"], y=df["Heating Cost"], line_kws={"color": "red"})

plt.title("Heating Cost vs Age with Regression Line")
plt.xlabel("Age")
plt.ylabel("Heating Cost")
plt.show()



"""Discussion

"""

